version: '3'
services:
  csgo:
    image: niflostancu/csgo-dedicated:latest
    network_mode: "host"
    volumes:
     - game:/home/steam/csgo-dedicated
    env_file: 
     - secrets.env
volumes:
  game:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './csgo-server/'

